
source:
  path: "hdfs:///Projects/synthetic/input/HEXAGON_SMALL.nt"
  geometryField: "http://geographica.di.uoa.gr/generator/landOwnership/asWKT"

target:
  path: "hdfs:///Projects/synthetic/input/HEXAGON_LARGE.nt"
  geometryField: "http://geographica.di.uoa.gr/generator/state/asWKT"

relation: "DE9IM"                                       # the target relation. With DE-9IM will discover all topological relations

# optional configurations
configurations:
  partitions: "12"
  thetaGranularity: "avg"                               # define the extend of dynamic tiling based on the geometries of source - Experiments have shown that "avg" is the best option
  gridType: "QUADTREE"    # allowed values:  KDBTREE, QUADTREE
  mainWF: "WF"                                          # specify main weighting function - allowed values: CF, JS, MBRO, PEARSON_X2, ISP
  secondaryWF: "WF"                                     # specify secondary weighting function - allowed values: CF, JS, MBRO, PEARSON_X2, ISP
  progressiveAlgorithm : "PA"                           # specify progressive algorithm - allowed values: PROGRESSIVE_GIANT, TOPK, RECIPROCAL_TOPK & RANDOM
  budget: "BU"                                          # the budget of progressive algorithms
